### ISSUE TITLE
색상 hex 코드 만들기

### ISSUE THREAD

**Issue by dev2820** [team-naming-1-hour/sweater#11]
사용하기로한 색상에 해당하는 hex 정보를 가지고, 색상을 분류한다.

### 색 종류

흰색
라이트그레이
회색
다크 그레이
검정
딥 레드
빨간색
분홍색
피치
코랄
주황색
아이보리

노란색
머스타드
네온 그린
라이트 그린
민트
녹색
올리브 그린
카키
다크 그린
스카이 블루
파란색
네이비
라벤더
보라색
버건디
갈색
레드 브라운
카키 베이지
카멜
샌드
베이지
연청
중청
진청
흑청

Done 조건: 색상 이름, 색상 hex 정보를 json 형태로 저장해 discord에 올리고 공유하면 Done

**Comment by Tuna-is-DW** [comment]
notion archive에 등록함
