### ISSUE TITLE
인스타 셀럽 전신 사진 크롤링

### ISSUE THREAD

**Issue by dev2820** [team-naming-1-hour/sweater#12]
코디 정보를 뽑기 위해 전신이 나온 셀럽 사진을 크롤링한다.
인스타에서 OOTD, today coordi 등을 검색해 나온 사진을 크롤링한다.

Done 조건: 1000장 채우고 그 사실을 공유하면 Done

**Comment by Jiwonii97** [comment]
오오티디, 데일리코드, 데일리룩, 투데이코드 카테고리로 총 약 3천장의 전신 사진을 크롤링 완료하였고, 구글 공유 드라이브에 업로드 완료하였다.
