### ISSUE TITLE
날씨 API 키 발급 받기

### ISSUE THREAD

**Issue by Jiwonii97** [team-naming-1-hour/sweater#15]
한명이 키 값을 신청하여 키를 발급 받고 API를 연동하기 위한 준비를 한다

Done 조건 : 공공데이터 포털을 통해 API Key값을 신청하고 받아 디스코드에 공유하면 Done

**Comment by Jiwonii97** [comment]
승인 완료

일반 인증키(Encoding) : hIvwxG8axkqd1LK7u5zVqxtoJ2FOecV6JY5UuHS8aNTQUwpabFhi7grMrvYUpFMmf3F4dp9Eexe9CEZzxPkC6w%3D%3D

일반 인증키(Decoding) : hIvwxG8axkqd1LK7u5zVqxtoJ2FOecV6JY5UuHS8aNTQUwpabFhi7grMrvYUpFMmf3F4dp9Eexe9CEZzxPkC6w==

**Comment by dev2820** [comment]
LGTM

**Comment by Tuna-is-DW** [comment]
lgtm

**Comment by spaff13** [comment]
lgtm
