### ISSUE TITLE
무신사 크롤링

### ISSUE THREAD

**Issue by Jiwonii97** [team-naming-1-hour/sweater#6]
무신사에서 카테고리 39개의 데이터를 크롤링한다. 최대 2000장

## 옷 종류
1. 상의 : 셔츠/남방, 블라우스, 맨투맨, 후드티, 니트/스웨터, 긴팔티, 트레이닝 상의, 반팔티, 민소매/나시, 카라티셔츠
2. 아우터 : 후드집업, 코트, 블루종, 레더/라이더스 재킷, 무스탕, 퍼, 항공점퍼, 블레이저, 청자켓/트러커 재킷, 가디건, 아노락 재킷, 플리스, 저지/트레이닝 재킷, 야구잠바/스타디움 재킷, 롱패딩, 숏패딩, 조끼, 사파리재킷/야상, 코치재킷
3. 하의 : 청바지, 반바지, 레깅스, 슬랙스, 면바지, 조거팬츠, 트레이닝 하의
4. 스커트 : 미니스커트, 롱 스커트, 원피스

Done 조건: 구글 드라이브에 크롤링한 사진을 업로드하고 카테고리별로 몇 장 크롤링됐는지 디스코드에 올리면 Done

**Comment by dev2820** [comment]
잘못 크롤링된 데이터가 있다하여, 2022-03-25 내에 다시 크롤링하기로함

**Comment by Jiwonii97** [comment]
무신사 이미지 크롤링 및  드라이브 업로드 완료

---
가디건	6660
레더 재킷 라이더스 재킷	2160
롱패딩	1080
무스탕	990
블레이저	5670
블루종	3060
사파리재킷 야상	1530
숏패딩	4860
아노락 재킷	3150
야구잠바 스타디움 재킷	810
저지 트레이닝 재킷	2070
조끼	4500
청자켓 트러커 재킷	2340
코치재킷	4950
코트	6120
퍼	1710
플리스	3870
항공점퍼	2700
후드 집업	5760

레깅스	2610
면바지	9810
미니스커트	3690
미디 스커트 롱 스커트	2790
반바지	11970
슬랙스	8190
조거팬츠	17100
트레이닝 하의	17370
청바지	10890

긴팔티	38160
맨투맨	34650
니트 스웨터	14490
블라우스	21060
셔츠 남방	16920
후드티	19620
민소매 나시	3780
반팔티	56160
카라 티셔츠	6570

원피스	9990
